CC = gcc
CFLAGS = -g -Wall -ansi -pedantic
EJS = p1
######################################################################################################################################

all: $(EJS)

p1:
	$(CC) $(CFLAGS) main.c state.c state.h afnd.c afnd.h transforma.c transforma.h -o p1

clean:
	rm -rf *o. $(EJS)
